update
Signed-off-by: Thomas Tai <thomastai@renaelectronics.com>

diff --git a/src/emc/usr_intf/renaconf/Debian/renaconf/debian/renaconf/DEBIAN/postinst b/src/emc/usr_intf/renaconf/Debian/renaconf/debian/renaconf/DEBIAN/postinst
--- a/src/emc/usr_intf/renaconf/Debian/renaconf/debian/renaconf/DEBIAN/postinst
+++ b/src/emc/usr_intf/renaconf/Debian/renaconf/debian/renaconf/DEBIAN/postinst
@@ -1,7 +1,66 @@
 #!/bin/sh
+# postinst script for renaconf
+#
+# see: dh_installdeb(1)
+
 set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
 # Automatically added by dh_pysupport
 if which update-python-modules >/dev/null 2>&1; then
 	update-python-modules  renaconf.public
 fi
 # End automatically added section
+
+
+# remove modules
+modprobe -r ppdev
+modprobe -r lp
+modprobe -r parport_pc
+modprobe -r parport
+
+# find the ioaddr
+IOADDR=`lspci -v -d 1c00:3050 | grep 'I/O ports at' | grep size=4 |cut -d " " -f 4`
+
+# add parport_pc.conf
+echo "options parport_pc io=0x${IOADDR} irq=none" > /etc/modprobe.d/parport_pc.conf
+echo "KERNEL==\"parport0\", MODE=\"0666\"" > /etc/udev/rules.d/10-renaconf.rules
+
+# insert modules
+modprobe parport 
+modprobe parport_pc io=0x${IOADDR} irq=none
+modprobe lp
+modprobe ppdev
+
+# set permission
+chmod 0666 /dev/parport0
+
+exit 0
